name: CI

on:
  push:
    branches: ["main"] # replace "main" with the default branch
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: leanprover/lean-action@v1
        with:
          lake-package-directory: arithmetic

      - uses: leanprover/lean-action@v1
        with:
          lake-package-directory: untyped

      - uses: leanprover/lean-action@v1
        with:
          lake-package-directory: typed
